# Generated by Django 5.0.2 on 2024-03-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComicsIO', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['comic']},
        ),
        migrations.RenameField(
            model_name='comic',
            old_name='nombre',
            new_name='comic',
        ),
    ]
