# Generated by Django 5.0.2 on 2024-03-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicsIO', '0002_alter_comic_options_rename_nombre_comic_comic'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuscarComic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDelcomic', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
